# Generated by Django 6.0.3 on 2026-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoption',
            name='plan_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('FULL_COURSE', 'Full Course')], max_length=20),
        ),
    ]
