# Generated by Django 6.0.2 on 2026-03-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='courseitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at']},
        ),
    ]
