# Generated by Django 6.0.2 on 2026-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_options_alter_courseitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Unnamed Course', max_length=255),
        ),
    ]
