# Generated by Django 6.0.2 on 2026-03-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_items/'),
        ),
    ]
