# Generated by Django 6.0.3 on 2026-04-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Bunny video URL for recorded sessions', null=True),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='type',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('ASSIGNMENT', 'Assignment'), ('MEETING', 'Online Meeting'), ('ANNOUNCEMENT', 'Announcement'), ('RECORDED_SESSION', 'Recorded Session')], max_length=20),
        ),
    ]
