# Generated by Django 6.0.3 on 2026-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseitem_video_url_alter_courseitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='video_url',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='video_id',
            field=models.CharField(blank=True, help_text='Vimeo video ID for recorded sessions', max_length=255, null=True),
        ),
    ]
